name: Entrega continua

on:
  workflow_call:

jobs:

  EC2:
    runs-on: ubuntu-latest
    steps:  
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: programa
    - uses: actions/checkout@v3

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /home/${{ secrets.REMOTE_USER }}
        EXCLUDE: "/dist/, /node_modules/, postgres-data"
        SCRIPT_BEFORE: |
          whoami
          ls -al
        SCRIPT_AFTER: |
          whoami
          ls -al
          echo $RSYNC_STDOUT 

    - name: Execute remote SSH commands using key
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.REMOTE_HOST}}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          export HOST=${{ secrets.REMOTE_HOST }}
          export USER=${{ secrets.REMOTE_HOST }}
          export PASSWORD=${{ secrets.REMOTE_HOST }}
          export DBNAME=${{ secrets.REMOTE_HOST }}
          export PORT=${{ secrets.REMOTE_HOST }}

